# Generated by Django 2.2.5 on 2021-01-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210105_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superhose',
            new_name='superhost',
        ),
    ]
